name: Scaffold Terraform Module
description: Scaffold Terraform Module
inputs:
  github_token:
    description: |
      GitHub Access Token
      contents:write - Create branches
      If skip_create_pr is false
      pull-requests:write - Create pull requests
    required: true

  module_path:
    description: 'Module path'
    required: true

runs:
  using: composite
  steps:
    - run: |
        echo "::error ::github_token is required"
        exit 1
      shell: bash
      if: inputs.github_token == ''
    - run: |
        echo "::error ::module_path is required"
        exit 1
      shell: bash
      if: inputs.module_path == ''

    - run: |
        if [ -e "${MODULE_PATH}" ]; then
          echo "::error ::file exists"
          exit 1
        fi
      shell: bash
      env:
        MODULE_PATH: ${{inputs.module_path}}

    - uses: suzuki-shunsuke/tfaction/get-global-config@main
      id: global-config

    - run: |
        mkdir -p "$(dirname "$MODULE_PATH")"
      shell: bash
      env:
        MODULE_PATH: ${{inputs.module_path}}

    - run: cp -R "${GITHUB_ACTION_PATH}/template" "$MODULE_PATH"
      shell: bash
      env:
        MODULE_PATH: ${{inputs.module_path}}

    - run: |
        sed -i "s|%%MODULE_NAME%%|$(basename "$MODULE_PATH")|g" "${MODULE_PATH}/docs/header.md"
      shell: bash
      env:
        MODULE_PATH: ${{inputs.module_path}}

    - run: |
        sed -i "s|%%MODULE_PATH%%|$MODULE_PATH|g" "${MODULE_PATH}/docs/header.md"
      shell: bash
      env:
        MODULE_PATH: ${{inputs.module_path}}

    - run: |
        sed -i "s|%%GITHUB_REPOSITORY%%|$GITHUB_REPOSITORY|g" "${MODULE_PATH}/docs/header.md"
      shell: bash
      env:
        MODULE_PATH: ${{inputs.module_path}}

    - run: |
        sed -i "s|%%REF%%|module_${MODULE_PATH/\//_}_v0.1.0|g" "${MODULE_PATH}/docs/header.md"
      shell: bash
      env:
        MODULE_PATH: ${{inputs.module_path}}

    - run: aqua init
      shell: bash
      working-directory: ${{inputs.module_path}}
      if: env.TFACTION_SKIP_ADDING_AQUA_PACKAGES != 'true'

    - run: aqua g -i hashicorp/terraform
      shell: bash
      working-directory: ${{inputs.module_path}}
      if: env.TFACTION_SKIP_ADDING_AQUA_PACKAGES != 'true'

    - run: aqua g -i aquasecurity/tfsec
      shell: bash
      working-directory: ${{inputs.module_path}}
      if: env.TFACTION_SKIP_ADDING_AQUA_PACKAGES != 'true' && fromJSON(steps.global-config.outputs.enable_tfsec)

    - run: aqua g -i aquasecurity/trivy
      shell: bash
      working-directory: ${{inputs.module_path}}
      if: env.TFACTION_SKIP_ADDING_AQUA_PACKAGES != 'true' && fromJSON(steps.global-config.outputs.enable_trivy)

    - run: aqua g -i terraform-linters/tflint
      shell: bash
      working-directory: ${{inputs.module_path}}
      if: env.TFACTION_SKIP_ADDING_AQUA_PACKAGES != 'true' && fromJSON(steps.global-config.outputs.enable_tflint)

    - run: aqua i -l -a
      shell: bash
      working-directory: ${{inputs.module_path}}

    - run: terraform-docs . > README.md
      shell: bash
      working-directory: ${{inputs.module_path}}

    - run: |
        echo "branch=scaffold-module-${MODULE_PATH/\//_}-$(date +%Y%m%dT%H%M%S)" >> "$GITHUB_OUTPUT"
      id: branch
      shell: bash
      env:
        MODULE_PATH: ${{inputs.module_path}}

    - run: git add "$MODULE_PATH"
      shell: bash
      env:
        MODULE_PATH: ${{inputs.module_path}}

    - run: |
        git diff --cached --name-only |
          xargs ghcp commit -r "$GITHUB_REPOSITORY" \
            -b "${{steps.branch.outputs.branch}}" \
            -m "chore($MODULE_PATH): scaffold a Terraform Module"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        MODULE_PATH: ${{inputs.module_path}}

    - run: |
        draft_pr=""
        if [ "${{steps.global-config.outputs.draft_pr}}" = "true" ]; then
          draft_pr="-d "
        fi
        cat << EOS >> "$GITHUB_STEP_SUMMARY"

        ## Create a pull request
        
        Please run the following command in your terminal.

        $CODE_BLOCK
        gh pr create -R "$GITHUB_REPOSITORY" $draft_pr\\
          -H "${{steps.branch.outputs.branch}}" \\
          -t "Scaffold a Terraform Module (${MODULE_PATH})" \\
          -b "This pull request was created by [GitHub Actions]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"
        $CODE_BLOCK

        [Reference](https://suzuki-shunsuke.github.io/tfaction/docs/feature/skip-creating-pr)
        EOS
      if: "fromJSON(steps.global-config.outputs.skip_create_pr)"
      shell: bash
      env:
        MODULE_PATH: ${{inputs.module_path}}
        CODE_BLOCK: "```"

    - run: |
        opts=(-H "${{steps.branch.outputs.branch}}" -a "$GITHUB_ACTOR" -t "Scaffold a Terraform Module (${MODULE_PATH})" -b "@$GITHUB_ACTOR This pull request was created by [GitHub Actions workflow_dispatch event]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)")
        if [ "${{steps.global-config.outputs.draft_pr}}" = "true" ]; then
          opts+=( -d )
        fi
        gh pr create "${opts[@]}"
      shell: bash
      if: "!fromJSON(steps.global-config.outputs.skip_create_pr)"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        MODULE_PATH: ${{inputs.module_path}}
